Repository voxpupuli/rspec-puppet-facts, pull requests merged in 2024-06, with the labels that each got.

#177 replace chained unless&if logic to make it more readable
  lib/rspec-puppet-facts.rb
Labels: skip-changelog

#178 Rely on modern facts
  lib/rspec-puppet-facts.rb
  spec/rspec_puppet_facts_spec.rb
Labels: backwards-incompatible

#175 work with symbolized strings
  .rubocop_todo.yml
  lib/rspec-puppet-facts.rb
  rspec-puppet-facts.gemspec
  spec/fixtures/metadata.json
  spec/rspec_puppet_facts_spec.rb
Labels: enhancement

#176 Require FacterDB 2.x
  .rubocop_todo.yml
  rspec-puppet-facts.gemspec
  spec/fixtures/metadata.json
  spec/rspec_puppet_facts_spec.rb
Labels: backwards-incompatible

#184 make code more readable
  .rubocop.yml
  lib/rspec-puppet-facts.rb
Labels: skip-changelog

#185 Release 4.0.0
  CHANGELOG.md
  lib/rspec-puppet-facts/version.rb
Labels: skip-changelog

#187 Switch to FacterDB 3 / drop legacy facts
  rspec-puppet-facts.gemspec
  spec/fixtures/metadata.json
  spec/rspec_puppet_facts_spec.rb
Labels: backwards-incompatible

#191 handle stringified facterversion properly
  lib/rspec-puppet-facts.rb
Labels: bug
