Repository voxpupuli/rspec-puppet-facts, pull requests merged in 2025-04, with the labels that each got.

#203 Only store facter versions in JSON
  README.md
  Rakefile
  ext/puppet_agent_components.json
  ext/puppet_agent_facter_versions.json
  lib/rspec-puppet-facts.rb
  spec/rspec_puppet_facts_spec.rb
Labels: enhancement

#204 Add Puppet 8.12 / Facter 4.12
  ext/puppet_agent_facter_versions.json
Labels: enhancement

#205 Release 5.3.0
  CHANGELOG.md
  lib/rspec-puppet-facts/version.rb
Labels: skip-changelog

#207 Fix compatibility with Ruby 2.7
  lib/rspec-puppet-facts.rb
  spec/rspec_puppet_facts_spec.rb
Labels: bug

#208 release 5.3.1
  CHANGELOG.md
  lib/rspec-puppet-facts/version.rb
Labels: skip-changelog
